# Generated by Django 3.2.7 on 2021-11-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-id',), 'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображении продуктов'},
        ),
    ]
