# Generated by Django 3.2.7 on 2021-11-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-id',), 'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
