# Generated by Django 3.2.7 on 2021-11-02 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Картинки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categry_image', to='categories.category')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображении продуктов',
                'ordering': ('-id',),
            },
        ),
    ]
